DROP TYPE IF EXISTS fltrenditem CASCADE;
CREATE TYPE fltrenditem AS (
        fltrenditem_flhead_id integer,
        fltrenditem_username text,
        fltrenditem_order integer,
        fltrenditem_level integer,
        fltrenditem_subgrp integer,
        fltrenditem_type text,
        fltrenditem_type_id integer,
        fltrenditem_parent_id integer,
        fltrenditem_accnt_id integer,
        fltrenditem_name text,
        fltrenditem_fld1 text,
        fltrenditem_fld2 text,
        fltrenditem_fld3 text,
        fltrenditem_fld4 text,
        fltrenditem_fld5 text,
        fltrenditem_fld6 text,
        fltrenditem_fld7 text,
        fltrenditem_fld8 text,
        fltrenditem_fld9 text,
        fltrenditem_fld10 text,
        fltrenditem_fld11 text,
        fltrenditem_fld12 text,
        fltrenditem_grndttl text
);
