language: node_js
sudo:     required
dist:     trusty
node_js:
  - "0.10"
addons:
  postgresql: 9.3

install:
  - git merge origin/$TRAVIS_BRANCH
  - pg_lsclusters
  - bash scripts/install_xtuple.sh -ipn -d 9.3
  - scripts/build_app.js

before_script:
  - cd node-datasource
  - node main.js > thelog.txt 2>&1 &
  - sleep 10
  - cd ..

script:
  - /usr/local/bin/npm run-script test-datasource
  - /usr/local/bin/npm run-script test
  - /usr/local/bin/npm run-script test-database
  - /usr/local/bin/npm run-script jshint

after_failure:
  - sudo tail -n 10000 thelog.txt
  - for LOGF in `sudo ls /var/log/postgresql` ; do echo == $LOGF ============= ; sudo tail -n 10000 /var/log/postgresql/$LOGF ; done
  - sudo grep -r oom /var/log
