DROP FUNCTION IF EXISTS asofinvbal(INTEGER, DATE);
DROP FUNCTION IF EXISTS asofinvnn(INTEGER, DATE);
DROP FUNCTION IF EXISTS asofinvqty(INTEGER, DATE);
DROP FUNCTION IF EXISTS forwardUpdateItemsite(INTEGER);
DROP FUNCTION IF EXISTS postValueintoInvBalance(INTEGER, DATE, NUMERIC, NUMERIC, NUMERIC, NUMERIC);
DROP FUNCTION IF EXISTS apCurrGain(INTEGER, INTEGER, NUMERIC, DATE);
DROP FUNCTION IF EXISTS arCurrGain(INTEGER, INTEGER, NUMERIC, DATE);
